TableBanking/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tLoans.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

tLoans/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('short-term/', views.ShortTerm.as_view(), name='short-term'),
    path('long-term/', views.LongTerm.as_view(), name='long-term'),
    path('savings/add/', views.AddSavings.as_view(), name='add-saving'),
    path('savings/remove', views.DeductSaving.as_view(), name='remove-saving'),
    path('loan/information/', views.LoanInformation.as_view(), name='loan_information'),
    path('boosters/', views.SaveBooster.as_view(), name='save_booster'),



    # delete short term
    path('delete/short-term/<int:pk>/', views.DeleteShortTermLoan.as_view(), name='delete-short-term'),
    # delete long term
    path('delete/long-term/<int:pk>/', views.DeleteLongTermLoan.as_view(), name='delete-long-term'),
    # delete long term amount
    path('delete/long-term-amount/<int:pk>/', views.DeleteLongTermPayment.as_view(), name='delete-long-term-amount')

]

tLoans/models.py
from django.db import models

# Create your models here.

PAYMENT_PERIODS = (
	('OM', 'One Month'),
	('TM', 'Three Months')
)

PAYMENT_PERIODS_2 = (
	('TF', 'Twenty Four Months'),
	('TS', 'Thirty Six Months')
)

BOOSTER_TYPES = (
	('AG', 'Agriculture'),
	('ED', 'Education')
)

class Saving(models.Model):
	name = models.CharField(max_length=20, default='Saving')
	amount = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.name


class Booster(models.Model):
	name = models.CharField(max_length=20, choices=BOOSTER_TYPES)
	amount = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


	def booster_percent(self):
		return ((self.amount * 50) / 100) + self.amount

	def __str__(self):
		return f"{self.amount}"



class Repayment(models.Model):
	name = models.CharField(max_length=20)
	amount = models.IntegerField()

	def __str__(self):
		return self.name


class ShortTermInterest(models.Model):
	amount = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f"{self.amount}"


class LongTermInterest(models.Model):
	amount = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return f"{self.amount}"


class Short_term(models.Model):
	name = models.CharField(max_length=20, default='Short Term')
	amount = models.IntegerField()
	payment_period = models.CharField(max_length=2, choices=PAYMENT_PERIODS)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	paid_months = models.ManyToManyField('Repayment', blank=True, null=True, related_name='short_terms')

	def first_second_month(self):
		total = (self.amount * 10) / 100
		return total 
	
	def final_amount(self):
		interest = (self.amount * 10) / 100
		total = self.amount + interest
		return total


	def save(self, *args, **kwargs):

		if ShortTermInterest.objects.all().exists() == True:
			current_interest = ShortTermInterest.objects.all().last().amount
		else:
			current_interest = 0

	
		short_term_interest_repayment = ((self.first_second_month()) * 1) / 100

		interest = ShortTermInterest()
		interest.amount = short_term_interest_repayment + current_interest
		interest.save()
		super(Short_term, self).save(*args, **kwargs)


	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Short Term'
		verbose_name_plural = 'Short Terms'





class Long_term(models.Model):
	name = models.CharField(max_length=20, default='Long Term')
	amount = models.IntegerField()
	amount_left = models.IntegerField(blank=True, null=True)
	payment_period = models.CharField(max_length=2, choices=PAYMENT_PERIODS_2)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


	def monthly_return_amount(self):
		if self.payment_period == "TS":
			return (self.amount / 36) * 1.12
		return (self.amount / 24) * 1.12


	def __str__(self):
		return self.name 


	class Meta:
		verbose_name = 'Long Term'
		verbose_name_plural = 'Long Terms'

tLoans/forms.py
from django import forms
from .models import Short_term, Long_term, Saving, Booster



class ShortTermForm(forms.ModelForm):
  
  class Meta:
    model = Short_term
    fields = ('amount', 'payment_period')
    widgets = {
      'amount': forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Amount to loan...',
        'type': 'number'
      }),
      'payment_period': forms.Select(attrs={
        'class': 'form-control',
        'name': 'loan-period',
        'required': 'required'
      })
    }


class LongTermForm(forms.ModelForm):

  class Meta:
    model = Long_term
    fields = ('amount', 'payment_period')
    widgets = {
      'amount': forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Amount to loan...',
        'type': 'number'
      }),
      'payment_period': forms.Select(attrs={
        'class': 'form-control',
        'name': 'payment-period',
        'required': 'required'
      })
    }

class ReturnShortLoan(forms.ModelForm):

  class Meta:
    model = Short_term
    fields = ('amount',)
    widgets = {
      'amount': forms.NumberInput(attrs={
        'class': 'form-control',
        'type': 'number',
        'placeholder': 'Amount to repay...'
      })
    }

class ReturnLongTerm(forms.ModelForm):

  class Meta:
    model = Long_term
    fields = ('amount',)
    widgets = {
      'amount': forms.NumberInput(attrs={
        'class': 'form-control',
        'type': 'number',
        'placeholder': 'Amount to repay...'
      })
    }


class SavingForm(forms.ModelForm):

  class Meta:
    model = Saving
    fields = ('amount',)
    widgets = {
      'amount': forms.NumberInput(attrs={
        'type': 'number',
        'placeholder': 'Amount to save...',
        'class': 'form-control'
      })
    }

class RemoveSavingForm(forms.ModelForm):

  class Meta:
    model = Saving
    fields = ('amount',)
    widgets = {
      'amount': forms.NumberInput(attrs={
        'type': 'number',
        'placeholder': 'Amount to deduct...',
        'class': 'form-control'
      })
    }

class BoosterForm(forms.ModelForm):

  class Meta:
    model = Booster
    fields = ('name', 'amount')
    widgets = {
      'name': forms.Select(attrs={
        'class': 'form-control',
        'required': 'required'
      }),
      'amount': forms.NumberInput(attrs={
        'type': 'number',
        'placeholder': 'Amount to save...',
        'class': 'form-control',
        'required': 'required'
      })
    }

tLoans/views.py
from django.shortcuts import render

from .forms import (ShortTermForm, 
                   ReturnShortLoan, 
                   LongTermForm, 
                   ReturnLongTerm, 
                   SavingForm, 
                   RemoveSavingForm, 
                   BoosterForm)

from django.views import View

from django.shortcuts import redirect

from .models import Short_term, Repayment, ShortTermInterest, Long_term, LongTermInterest, Saving, Booster

from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
class Home(LoginRequiredMixin, View):
  def get(self, request):
    context = {
      'form': ShortTermForm,
      'form2': LongTermForm,
      'saving_form': SavingForm,
      'saving': Saving.objects.all().last(),
      'remove_saving_form': RemoveSavingForm,
      'short_loans': Short_term.objects.all(),
      'long_loans': Long_term.objects.all()
    }
    return render(self.request, 'tLoans/home.html', context)

  def post(self, request):
    # get form data
    form = ShortTermForm(request.POST or None)
    form2 = LongTermForm(request.POST or None)
    if form.is_valid():
      amount = form.cleaned_data.get('amount')
      payment_period = form.cleaned_data.get('payment_period')


      # validation
      if int(amount) < 1:
        messages.error(request, 'You cannot loan that amount')
        return redirect('home')
      else:
        # save short term loan request
        loan = Short_term(
          amount=amount,
          payment_period=payment_period
        )
        loan.save()
        messages.success(request, 'You have successfully made a loan')
        return redirect('short-term')

    if form2.is_valid():
      amount = form2.cleaned_data.get('amount')
      payment_period = form2.cleaned_data.get('payment_period')

      # validation
      if int(amount) < 1:
        messages.error(request, "You cannot loan that amount")
        return redirect('homt')
      else:
        loan = Long_term(
          amount = amount,
          payment_period = payment_period
        )
        loan.save()
        messages.success(request, "You have successfully made a loan")
        return redirect('long-term')
    messages.error(self.request, 'Something went wrong')
    return redirect('home')

# add short term
class ShortTerm(LoginRequiredMixin, View):
  def get(self, *args, **kwargs):
    context = {
      'form': ReturnShortLoan,
      'loans': Short_term.objects.all(),
      'repayments': Repayment.objects.filter(name='Short Term')
    }
    return render(self.request, 'tLoans/short_term.html', context)


  def post(self, request, *args, **kwargs):
    # get form data
    form = ReturnShortLoan(self.request.POST or None)
    if form.is_valid():
      amount = form.cleaned_data.get('amount')

      first_two_months_amount = Short_term.objects.all()[0].first_second_month()
      final_month_amount = Short_term.objects.all()[0].final_amount()
      
      

      if amount != first_two_months_amount and amount != final_month_amount:
        messages.error(request, "You cannot repay that amount")
        return redirect('short-term')
      else:
        loan = Short_term.objects.all()[0]

        repayment = Repayment(
          name = "Short Term",
          amount = amount
        )
        repayment.save()
        loan.paid_months.add(repayment.id)
      return redirect('short-term')

# add long term
class LongTerm(LoginRequiredMixin, View):
  def get(self, *args, **kwargs):
    context = {
      'form': ReturnLongTerm(),
      'loans': Long_term.objects.all(),
      'repayments': Repayment.objects.filter(name='Long Term')
    }
    return render(self.request, 'tLoans/long_term.html', context)

  def post(self, *args, **kwargs):

    # get form data
    form = ReturnLongTerm(self.request.POST or None)
    if form.is_valid():
      amount = form.cleaned_data.get('amount')
      
      loan = Long_term.objects.all().first()

      # validation
      if int(amount) >= loan.monthly_return_amount():
        # subtract from loaned amount
        if not loan.amount_left:
          loan.amount_left = loan.amount


        # add payment to repayment
        repayment = Repayment(
          name = "Long Term",
          amount = amount
        )

        # add long term interest repayment
        if loan.payment_period == 'TF':
          total = (loan.amount / 24) 
        else:
           total = (loan.amount / 36)

        if LongTermInterest.objects.all().exists() == True:
          current_interest = LongTermInterest.objects.all().last().amount
        else:
          current_interest = 0

        long_term_interest_repayement = (total * 1.12) - total
        loan.amount_left -= (amount - long_term_interest_repayement)

        interest = LongTermInterest(
          amount = long_term_interest_repayement + current_interest
        )
        loan.save()
        repayment.save()
        interest.save()

        # check if loan is completed:
        if not loan.amount_left > 0:
          messages.success(self.request, "You have finished repaying your loan")
          return redirect('long-term')
      else:
        messages.error(self.request, 'You cannot pay that amount')
        return redirect('long-term')
    return redirect('long-term')

# save booster
class SaveBooster(LoginRequiredMixin, View):
  def get(self, *args, **kwargs):
    context = {
      'form': BoosterForm,
      'education': Booster.objects.filter(name='ED').last(),
      'agriculture': Booster.objects.filter(name='AG').last()
    }
    return render(self.request, "tLoans/boosters.html", context)

  def post(self, *args, **kwargs):
    form = BoosterForm(self.request.POST or None)
    if form.is_valid():
      amount = form.cleaned_data.get('amount')
      name = form.cleaned_data.get('name')

      booster = Booster()

      # check current booster
      if amount >= 200:
        if Booster.objects.filter(name=name).exists() == True:
          current_booster = Booster.objects.filter(name=name).last().amount
          booster.name = name
          booster.amount += (amount + current_booster)
          booster.save()
          messages.success(self.request, 'Booster successfully added')
          return redirect('save_booster')
        else:
          booster.name = name
          booster.amount = amount
          booster.save()
          messages.success(self.request, 'Booster successfully added')
          return redirect('save_booster')
      messages.error(self.request, 'You cannot save that amount')
      return redirect('save_booster')

      return redirect('save_booster')



# Add savings
class AddSavings(LoginRequiredMixin, View):
  def post(self, *args, **kwargs):
    form = SavingForm(self.request.POST or None)
    if form.is_valid():
      amount = form.cleaned_data.get('amount')

      # check if there's a saving
      if Saving.objects.all().first():
        current_amount = Saving.objects.all().last().amount
      else:
        current_amount = 0
      
      saving = Saving()
      if amount < 2000:
        messages.error(self.request, "You cannot save that amount")
        return redirect('home')
      else:
        saving.amount = (amount + current_amount)
        saving.save()

        messages.success(self.request, 'Saving successfully added')
        return redirect('home') # return redirect to table
    messages.error(self.request, 'Something went wrong')
    return redirect('home')


# deduct savings
class DeductSaving(LoginRequiredMixin, View):
  def post(self, *args, **kwargs):
    form = RemoveSavingForm(self.request.POST or None)
    if form.is_valid():
      amount = form.cleaned_data.get('amount')

      saving = Saving.objects.all().last()
      if amount > saving.amount:
        messages.error(self.request, "You cannot deduct that amount")
        return redirect('home')
      else:
        saving.amount -= amount
        saving.save()
        messages.success(self.request, 'Amount successfully deducted from your savings')
        return redirect('home')
    messages.error(self.request, 'Something went wrong')
    return redirect('home')


class LoanInformation(View):
  def get(self, *args, **kwargs):
    context = {
      'saving': Saving.objects.all().last(),
      'short_term': Short_term.objects.all().first(),
      'long_term': Long_term.objects.all().first(),
      'short_term_interest': ShortTermInterest.objects.all().last(),
      'long_term_interest': LongTermInterest.objects.all().last(),
      'education': Booster.objects.filter(name='ED').last(),
      'agriculture': Booster.objects.filter(name='AG').last()
    }
    return render(self.request, 'tLoans/table.html', context)

# delete payment 
class DeleteLongTermPayment(LoginRequiredMixin, View):

  def get(self, request, pk):
    try:
      repayment = Repayment.objects.filter(name='Long Term', pk=pk)
      if repayment.exists():
        amount = repayment.first()
        amount.delete()

        # re-add amount to amount_left
        loan = Long_term.objects.all().first()
        loan.amount_left += amount.amount
        loan.save()
        return redirect('long-term')
    except ObjectDoesNotExist:
      messages.error(request, 'Something went wrong')
      return redirect('long-term')


# delete Short Terms
class DeleteShortTermLoan(LoginRequiredMixin, View):

  def get(self, request, pk):
    try:
      loan = Short_term.objects.filter(pk=pk)
      if loan.exists():
        loan = loan.first()
        loan.delete()
        messages.success(request, 'Loan successfully deleted')
        return redirect('home')
    except ObjectDoesNotExist:
      messages.error(request, 'Something went wrong')
      return redirect('short_term')

# delete long term Loan
class DeleteLongTermLoan(LoginRequiredMixin, View):

  def get(self, request, pk):
    try:
      loan = Long_term.objects.filter(pk=pk)
      if loan.exists():

templates/tLoans/boosters.html
{% extends 'base.html' %}

{% block content %}
<div id="short-term-hero-card">
    <div class="container">
        {% include 'tLoans/partials/_alerts.html' %}
        <div class="row justify-content-center">
            <div class="col">
                <div class="jumbotron p-3" id="jumbotron-short">
                    <div class="row">
                        <div class="col-lg-8">
                            <h6 id="short-loan-heading">BOOSTERS (Education &amp; agriculture)</h6>
                            <hr>
                            <small class="badge badge-light">Education Booster</small>
                            {% if education %}
                            <h6 id="short-term-loan-balance" class="repayment-box mt-2 text-left" style="font-size: 25px;font-weight:bold;">KES {{ education.amount }}</h6>
                            <small>Total Booster(Inc. interest): <b>KES {{ education.booster_percent | floatformat:0 }}</b> </small>
                            {% else %}
                            <h6 id="short-term-loan-balance" style="font-size:25px;font-weight:bold;">No Booster</h6>
                            {% endif %}
                            <hr>
                            <small class="badge badge-light">Agriculture Booster</small>
                            {% if agriculture %}
                            <h6 id="short-term-loan-balance" class="repayment-box mt-2 text-left" style="font-size: 25px;font-weight:bold;">KES {{ agriculture.amount }}</h6>
                            <small>Total Booster(Inc. interest): <b>KES {{ agriculture.booster_percent | floatformat:0 }}</b> </small>
                            {% else %}
                            <h6 id="short-term-loan-balance" style="font-size:25px;font-weight:bold;">No Booster</h6>
                            {% endif %}
                        </div>
                        <div class="col-lg-4 flex-column align-items-center align-self-center">
                            <h6 class="text-center" id="short-loan-heading">Save</h6>
                            <div class="short-term-modal">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <!-- <input class="form-control" type="number" name="short-loan" placeholder="Enter amount to save" /> -->
                                        {{ form.amount }}
                                    </div>
                                    <div class="form-check mb-3 mt-2 pl-0">
                                        <!-- <input class="form-check-input" type="radio" id="formCheck-2" name="booster-type" />
                                        <label class="form-check-label" for="formCheck-2">Booster type</label> -->
                                        {{ form.name }}
                                    </div>
                                    <button class="btn btn-dark btn-block btn-sm" type="submit">Save</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
</html>

templates/tLoans/long_term.html
{% extends 'base.html' %}

{% block content %}
<div id="short-term-hero-card">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                {% include 'tLoans/partials/_alerts.html' %}
                <div class="jumbotron p-3" id="jumbotron-short">
                    <div class="row">
                        {% for loan in loans %}
                        <div class="col-lg-8">
                            <h6 id="short-loan-heading">Long term loan</h6>
                            <hr>
                            <h6 class="repayment-box text-left" id="short-term-loan-balance" style="font-size:28px;font-weight:bold;">KES {{ loan.amount }}</h6>
                            
                            <small class="text-uppercase" id="payment-plan-heading">payment plan</small>
                            <div class="card" style="border: 0px;">
                                <div class="card-body modal-1 p-0">
                                    {% if loan.get_payment_period_display == 'Twenty Four Months' %}
                                    <small class="text-muted card-subtitle mb-2">Amount to be paid every month for 24 months</small>
                                    {% else %}
                                    <small class="text-muted card-subtitle mb-2">Amount to be paid every month for 36 months</small>
                                    {% endif %}
                                    <h6 id="short-term-loan-balance-1" style="font-size:25px;font-weight:bold;">KES {{ loan.monthly_return_amount | floatformat:0 }}</h6>
                                </div>
                            </div>
                            {% if loan.amount_left %}
                            <small>You have left to pay</small>
                            <h6 style="font-size:20px;font-weight:bold;">KES {{ loan.amount_left }}</h6>
                            {% endif %}
                            <hr>
                            <small>You have paid {{ repayments.count }} months</small>
                            {% if repayments %}
                            <div class="repayment-months-info my-2 scrollable" style="overflow-y: auto; height: 2rem;">
                                {% for item in repayments %}
                                    <small class="badge badge-pill badge-dark p-1">{{ forloop.counter }} payment made: KES {{ item.amount }} <a href="{% url 'delete-long-term-amount' item.pk %}" style="font-size: 12px;" class="text-warning"><i class="far fa-times-circle"></i></a></small>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                        {% if loan.amount_left != 0 %}
                        <div class="col-lg-4 flex-column align-items-center align-self-center">
                            <h6 class="text-center" id="short-loan-heading">repay</h6><div class="short-term-modal">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <!-- <input class="form-control" type="number" name="long-loan" placeholder="Enter amount to repay" /> -->
                                       {{ form.amount }}
                                    </div>
                                    <button class="btn btn-dark btn-block btn-sm" type="submit">Repay</button>
                                </form>
                            </div>
                        </div>
                        {% else %}
                        <div class="col-lg-4 flex-column align-items-center align-self-center text-center mt-3">
                            <i class="far fa-smile fa-2x text-center repayment-box"></i>
                        </div>
                        <a href="{% url 'delete-long-term' loan.pk %}" class="btn btn-danger btn-sm">Delete Loan</a>
                        {% endif %}
                        {% empty %}
                        <div class="col-lg-7 align-items-center align-self-center p-0 text-center">
                            <small>You have no <b>Long Term Loan</b></small>
                        </div>
                        <div class="col-lg-5">
                            <a href="{% url 'home' %}" class="btn btn-dark btn-block btn-sm">Make a Long Term Loan &longrightarrow;</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/tLoans/table.html
{% extends 'base.html' %}

{% block content %}
<div id="short-term-hero-card">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col">
                        <div class="jumbotron p-3" id="jumbotron-short">
                            <div class="row">
                                <div class="col">
                                    <h6 class="repayment-box text-left" id="short-loan-heading">Your contributions</h6>
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Normal Saving</th>
                                                    <th>Short Term Loan</th>
                                                    <th>Short Term Interest Repayment&nbsp;</th>
                                                    <th>Long Term Loan Balance&nbsp;</th>
                                                    <th>Long Term Interest Repayment&nbsp;</th>
                                                    <th>Educaton Booster</th>
                                                    <th>Agriculture Booster</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        {% if saving %}
                                                            {{ saving.amount }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if short_term %}
                                                            {{ short_term.amount }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if short_term_interest %}
                                                            {{ short_term_interest.amount }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if long_term %}
                                                            {{ long_term.amount_left }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if long_term_interest %}
                                                            {{ long_term_interest }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if education %}
                                                        {{ education.amount }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if agriculture %}
                                                        {{ agriculture.amount }}
                                                        {% else %}
                                                            -
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}